tkg:
  regions:
    - name: tkg-region-vsphere-20200312184000
      context: tkg-region-vsphere-20200312184000-admin@tkg-region-vsphere-20200312184000
      file: /Users/anujc/.kube/config
    - name: tkg-region-aws-20200312192017
      context: tkg-region-aws-20200312192017-admin@tkg-region-aws-20200312192017
      file: /Users/anujc/.kube/config
  current-region-context: tkg-region-aws-20200312192017-admin@tkg-region-aws-20200312192017
providers:
  - name: "my-infra-provider"
    url: "https://github.com/myorg/myrepo/releases/latest/infrastructure_components.yaml"
    type: "InfrastructureProvider"
  - name: "cluster-api" # override a pre-defined provider
    url: "https://github.com/myorg/myforkofclusterapi/releases/latest/core_components.yaml"
    type: "CoreProvider"
  - name: aws
    url: /Users/dummy/.tkg/providers/infrastructure-aws/v0.5.1/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: vsphere
    url: /Users/dummy/.tkg/providers/infrastructure-vsphere/v0.6.2/infrastructure-components.yaml
    type: InfrastructureProvider
  - name: vsphere
    url: /Users/dummy/.tkg/providers/infrastructure-vsphere/v0.7.0/infrastructure-components.yaml
    type: InfrastructureProvider

# Values for environment variable substitution
AWS_B64ENCODED_CREDENTIALS: XXXXXXXX
VSPHERE_PASSWORD: Admin!23
KUBERNETES_VERSION: v1.16.0+vmware.1
BAR: bar
AWS_ACCESS_KEY_ID: <encoded:UVdSRVRZVUlPUExLSkhHRkRTQVo=>
AWS_SECRET_ACCESS_KEY: uNncCatIvWu1e$rqwerkg35qU7dswfEa4rdXJk/E
VSPHERE_DATACENTER: datacenter
VSPHERE_TEMPLATE: photon-3-v1.16.0+vmware.1
AWS_REGION: us-east-2
AWS_NODE_AZ: us-east-2a
AWS_AMI_ID: ami-xxxxx
AWS_VPC_CIDR: "10.0.0.0/16"
AWS_PRIVATE_NODE_CIDR: "10.0.0.0/24"
AWS_PUBLIC_NODE_CIDR: "10.0.1.0/24"
AWS_NODE_AZ_1: us-east-2b
AWS_PRIVATE_NODE_CIDR_1: "10.0.2.0/24"
AWS_PUBLIC_NODE_CIDR_1: "10.0.3.0/24"
AWS_NODE_AZ_2: us-east-2c
AWS_PRIVATE_NODE_CIDR_2: "10.0.4.0/24"
AWS_PUBLIC_NODE_CIDR_2: "10.0.5.0/24"
VSPHERE_CONTROL_PLANE_DISK_GIB: "20"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "1"
VSPHERE_CONTROL_PLANE_MEM_MIB: "2048"
VSPHERE_WORKER_DISK_GIB: "20"
VSPHERE_WORKER_MEM_MIB: "2048"
VSPHERE_WORKER_NUM_CPUS: "1"
VSPHERE_HA_PROXY_MEM_MIB: "2048"
VSPHERE_HA_PROXY_DISK_GIB: "20"
VSPHERE_HA_PROXY_NUM_CPUS: "1"
WORKER_MACHINE_COUNT_0: "2"
WORKER_MACHINE_COUNT_1: "1"
WORKER_MACHINE_COUNT_2: "3"