name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, migrate-tkg-cli/* ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
      id: go

    - name: Use Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Config credentials
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        git config --global url."https://git:$GH_ACCESS_TOKEN@github.com".insteadOf "https://github.com"

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: make all

    - name: Test
      run: |
        make test
        make verify

  golangci-lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - ""
          - addons
          - addons/pinniped/post-deploy
    steps:
    - uses: actions/checkout@v2

    - name: Config credentials
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        git config --global url."https://git:$GH_ACCESS_TOKEN@github.com".insteadOf "https://github.com"

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.38.0
        args: --timeout=5m -v
        working-directory: ${{matrix.working-directory}}

    - name: Run vale doc linter
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        make doc-lint
