name: Plugin Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
    - 'cmd/cli/plugin/cluster/**'
    - 'cmd/cli/plugin/managementcluster/**'

jobs:
  build:
    name: Plugin Tests
    runs-on: ubuntu-latest
    steps:
    - name: Free disk space on runner
      run: sudo rm -rf /usr/share/dotnet

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Config credentials
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        git config --global url."https://git:$GH_ACCESS_TOKEN@github.com".insteadOf "https://github.com"

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: make build-cli-local

    - name: Update Version Selector
      run: make TANZU_PLUGIN_UNSTABLE_VERSIONS=experimental set-unstable-versions

    - name: Install Tanzu CLI
      run: make install-cli

    - name: Install CLI plugins
      run: make install-cli-plugins

    - name: Run cluster test plugin
      run: tanzu test plugin cluster



