name: TKG Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
    - 'pkg/v1/tkg/**'
    - 'pkg/v1/providers/**'
    - '.github/workflows/tkg_integration_tests.yaml'

jobs:
  build:
    name: TKG Integration Tests
    runs-on: tkg
    steps:
    - name: Free disk space on runner
      run: sudo rm -rf /usr/share/dotnet

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Config credentials
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        git config --global url."https://git:$GH_ACCESS_TOKEN@github.com".insteadOf "https://github.com"

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build Tools
      run: make tools

    - name: Extract PR Number
      uses: Dovyski/payload-info-action@master
      id: get_pr_num
      with:
        # when event is a pull request, obtaining the PR number is obvious
        filter_pull_request: '.number'
        # when event is a push (merge of PR), obtains original PR number from the merge commit message
        filter_push: '.head_commit.message | capture("Merge pull request #(?<pr>[[:digit:]]+)").pr | tonumber'

    - name: Find Comment
      uses: peter-evans/find-comment@v1
      id: findcomment
      with:
        issue-number: ${{ steps.get_pr_num.outputs.value }}
        body-includes: //usebom
        direction: last

    - name: Extract Alternate BOM
      shell: bash
      run: |
        export BOMCOMMENT=$(echo -e "${{ steps.findcomment.outputs.comment-body }}" | tr -d "[:space:]")
        echo "##[set-output name=bompath;]$(echo "$BOMCOMMENT" | awk -F : '{print $2}')"
        echo "##[set-output name=bomtag;]$(echo "$BOMCOMMENT" | awk -F : '{print $3}')"
      id: extract_bom

    - name: Cleanup
      run: rm -rf ~/.tanzu ~/.tkg ~/.config; docker kill $(docker ps -q) | true; docker system prune -a --volumes -f

    - name: Run TKG integration tests
      run: |
        if [[ ! -z "${{ steps.extract_bom.outputs.bompath }}" ]]; then
          export TKG_DEFAULT_BOM_IMAGE_PATH=${{ steps.extract_bom.outputs.bompath }}
        fi
        if [[ ! -z "${{ steps.extract_bom.outputs.bomtag }}" ]]; then
          export TKG_DEFAULT_BOM_IMAGE_TAG=${{ steps.extract_bom.outputs.bomtag }}
        fi
        make configure-bom
        E2E_CONFIG=$PWD/pkg/v1/tkg/test/config/docker.yaml hack/tools/bin/ginkgo -nodes=3 -v -trace pkg/v1/tkg/test/tkgctl/docker
