name: TKG Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
    - 'pkg/v1/tkg/**'
    - 'pkg/v1/providers/**'

jobs:
  build:
    name: TKG Integration Tests
    runs-on: ubuntu-latest
    steps:
    - name: Free disk space on runner
      run: sudo rm -rf /usr/share/dotnet

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Config credentials
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        git config --global url."https://git:$GH_ACCESS_TOKEN@github.com".insteadOf "https://github.com"

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build Tools
      run: make tools

    - name: Cleanup
      run: docker kill $(docker ps -q) | true; docker system prune -a --volumes -f

    - name: Run TKG integration tests
      run: E2E_CONFIG=$PWD/pkg/v1/tkg/test/config/docker.yaml hack/tools/bin/ginkgo -v -trace pkg/v1/tkg/test/tkgctl/docker
